Config = Config or {}

Config.RosterLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/1GFBu31UcrpLFPpqpy04XyzNpkBU0BKk9V2zuIE6pSCw/edit?usp=sharing',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['sasp'] = '',
    ['lawyer'] = '',
}


Config.UseWolfknightRadar = true
--[[
Adds support for Wraith ARS 2X by WolfKnight98 (wk_wars2x)
https://github.com/WolfKnight98/wk_wars2x
To save on unnecessary database queries, in wk_wars2x/config.lua set 'CONFIG.use_sonorancad = true'
This will only check plates of vehicles that have been occupied by a player
--]]

Config.OnlyShowOnDuty = true

Config.Fuel = "ps-fuel" -- "LegacyFuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'OFFENSES AGAINST PERSONS',
    [2] = 'OFFENSES INVOLVING THEFT',
    [3] = 'OFFENSES INVOLVING FRAUD',
    [4] = 'OFFENSES INVOLVING DAMAGE TO PROPERTY',
    [5] = 'OFFENSES AGAINST PUBLIC ADMINISTRATION',
    [6] = 'OFFENSES AGAINST PUBLIC ORDER',
    [7] = 'OFFENSES AGAINST HEALTH AND MORALS',
    [8] = 'OFFENSES AGAINST PUBLIC SAFETY',
    [9] = 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE',
    [10] = 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE',
}

-- Config.PenalCode = {
--     [1] = {
--         [1] = {title = 'Accessory to Felony', class = 'Felony', id = 'P.C. 3001', months = 30, fine = 5000, color = 'red'},
--         [2] = {title = 'Aircraft Hijacking', class = 'Felony', id = 'P.C. 3002', months = 90, fine = 10000, color = 'red'},
--         [3] = {title = 'Assisting An Offender', class = 'Felony', id = 'P.C. 3003', months = 15, fine = 2500, color = 'red'},
--         [4] = {title = 'Breach of Airspace Regulations', class = 'Felony', id = 'P.C. 3004', months = 60, fine = 20000, color = 'red'},
--         [5] = {title = 'Contempt of Court', class = 'Felony', id = 'P.C. 3005', months = 30, fine = 5000, color = 'red'},
--         [6] = {title = 'Escaping Lawful Custody', class = 'Felony', id = 'P.C. 3006', months = 30, fine = 8000, color = 'red'},
--         [7] = {title = 'Felony Evading Arrest', class = 'Felony', id = 'P.C. 3007', months = 15, fine = 2500, color = 'red'},
--         [8] = {title = 'Human Trafficking', class = 'Felony', id = 'P.C. 3008', months = 120, fine = 8000, color = 'red'},
--         [9] = {title = 'Impersonation of a Government Official', class = 'Felony', id = 'P.C. 3009', months = 60, fine = 10000, color = 'red'},
--         [10] = {title = 'Jailbreak', class = 'Felony', id = 'P.C. 3010', months = 90, fine = 7500, color = 'red'},
--         [11] = {title = 'Kidnapping', class = 'Felony', id = 'P.C. 3011', months = 20, fine = 3500, color = 'red'},
--         [12] = {title = 'Obstruction of a Government Official', class = 'Felony', id = 'P.C. 3012', months = 20, fine = 5000, color = 'red'},
--         [13] = {title = 'Obstruction of Justice', class = 'Felony', id = 'P.C. 3013', months = 20, fine = 5000, color = 'red'},
--         [14] = {title = 'Perjury', class = 'Felony', id = 'P.C. 3014', months = 60, fine = 7500, color = 'red'},
--         [15] = {title = 'Possession of Stolen Goods', class = 'Felony', id = 'P.C. 3015', months = 15, fine = 3000, color = 'red'},
--         [16] = {title = 'Prison Break', class = 'Felony', id = 'P.C. 3016', months = 60, fine = 10000, color = 'red'},
--         [17] = {title = 'Theft', class = 'Felony', id = 'P.C. 3017', months = 30, fine = 5000, color = 'red'},
--         [18] = {title = 'Trespassing on Airport Property', class = 'Felony', id = 'P.C. 3018', months = 30, fine = 10000, color = 'red'},
--         [19] = {title = 'Trespassing with the Intent of Theft', class = 'Felony', id = 'P.C. 3019', months = 30, fine = 5000, color = 'red'},
--         [20] = {title = 'Unlawful Imprisonment', class = 'Felony', id = 'P.C. 3020', months = 60, fine = 5000, color = 'red'},
--         [21] = {title = 'Witness Intimidation', class = 'Felony', id = 'P.C. 3021', months = 90, fine = 10000, color = 'red'},
--         [22] = {title = 'Grand Theft Auto', class = 'Felony', id = 'P.C. 3022', months = 10, fine = 1500, color = 'red'},
--         [23] = {title = 'Hit and Run', class = 'Felony', id = 'P.C. 3023', months = 60, fine = 2500, color = 'red'},
--         [24] = {title = 'Reckless Driving', class = 'Felony', id = 'P.C. 3024', months = 15, fine = 2000, color = 'red'},
--         [25] = {title = 'Vehicular Battery', class = 'Felony', id = 'P.C. 3025', months = 20, fine = 5000, color = 'red'},
--         [26] = {title = 'Art Gallery Heist', class = 'Felony', id = 'P.C. 3026', months = 45, fine = 25000, color = 'red'},
--         [27] = {title = 'Bank Robbery', class = 'Felony', id = 'P.C. 3027', months = 45, fine = 15000, color = 'red'},
--         [28] = {title = 'Jewelry Heist', class = 'Felony', id = 'P.C. 3028', months = 45, fine = 7500, color = 'red'},
--         [29] = {title = 'Store Robbery', class = 'Felony', id = 'P.C. 3029', months = 25, fine = 3500, color = 'red'},
--         [30] = {title = 'Armed Robbery', class = 'Felony', id = 'P.C. 3030', months = 40, fine = 8000, color = 'red'},
--         [31] = {title = 'Commercial break in', class = 'Felony', id = 'P.C. 3031', months = 40, fine = 8000, color = 'red'},
--     },
--     [2] = {
--         [1] = {title = 'Class 1 Drug Trafficking', class = 'Felony', id = 'P.C. 4001', months = 15, fine = 2500, color = 'red'},
--         [2] = {title = 'Class 2 Drug Trafficking', class = 'Felony', id = 'P.C. 4002', months = 20, fine = 5000, color = 'red'},
--         [3] = {title = 'Class 3 Drug Trafficking', class = 'Felony', id = 'P.C. 4003', months = 30, fine = 10000, color = 'red'},
--         [4] = {title = 'Drug Manufacture & Supply', class = 'Felony', id = 'P.C. 4004', months = 60, fine = 10000, color = 'red'},
--         [5] = {title = 'Industrial Scale Drug Manufacture & Supply', class = 'Felony', id = 'P.C. 4005', months = 180, fine = 50000, color = 'red'},
--         [6] = {title = 'Possession Of Class 2 Drug', class = 'Felony', id = 'P.C. 4006', months = 0, fine = 2000, color = 'red'},
--         [7] = {title = 'Possession Of Class 2 Drug With Intent To Supply', class = 'Felony', id = 'P.C. 4007', months = 15, fine = 3500, color = 'red'},
--         [8] = {title = 'Possession of Class 3 drug', class = 'Felony', id = 'P.C. 4008', months = 10, fine = 5000, color = 'red'},
--         [9] = {title = 'Possession of Class 3 Drug With Intent To Supply', class = 'Felony', id = 'P.C. 4009', months = 25, fine = 6000, color = 'red'},
--         [10] = {title = 'Brandishing a Weapon', class = 'Felony', id = 'P.C. 4010', months = 15, fine = 2000, color = 'red'},
--         [11] = {title = 'Illegal Weapons Crafting', class = 'Felony', id = 'P.C. 4011', months = 120, fine = 20000, color = 'red'},
--         [12] = {title = 'Illegal Weapons Trafficking', class = 'Felony', id = 'P.C. 4012', months = 240, fine = 50000, color = 'red'},
--         [13] = {title = 'Industrial scale Illegal Weapons Crafting', class = 'Felony', id = 'P.C. 4013', months = 360, fine = 100000, color = 'red'},
--         [14] = {title = 'Possession of a Firearm Without a License', class = 'Felony', id = 'P.C. 4014', months = 10, fine = 3000, color = 'red'},
--         [15] = {title = 'Possession of an Illegal Firearm Class 1', class = 'Felony', id = 'P.C. 4015', months = 20, fine = 5000, color = 'red'},
--         [16] = {title = 'Possession of an Illegal Firearm Class 2', class = 'Felony', id = 'P.C. 4016', months = 35, fine = 7000, color = 'red'},
--         [17] = {title = 'Possession of an Illegal Firearm Class 3', class = 'Felony', id = 'P.C. 4017', months = 60, fine = 12500, color = 'red'},
--         [18] = {title = 'Possession of Explosives', class = 'Felony', id = 'P.C. 4018', months = 20, fine = 5000, color = 'red'},
--         [19] = {title = 'Unlawful Discharge of a Firearm', class = 'Felony', id = 'P.C. 4019', months = 15, fine = 5000, color = 'red'},
--     },
--     [3] = {
--         [1] = {title = 'Assault', class = 'Felony', id = 'P.C. 5001', months = 15, fine = 2000, color = 'red'},
--         [2] = {title = 'Assault with a Deadly Weapon', class = 'Felony', id = 'P.C. 5002', months = 30, fine = 5000, color = 'red'},
--         [3] = {title = 'Attempted Murder', class = 'Felony', id = 'P.C. 5003', months = 45, fine = 7500, color = 'red'},
--         [4] = {title = 'Manslaughter', class = 'Felony', id = 'P.C. 5004', months = 25, fine = 5000, color = 'red'},
--         [5] = {title = 'Murder', class = 'Felony', id = 'P.C. 5005', months = 999999999, fine = 20000, color = 'red'},
--         [6] = {title = 'Terroristic Threat', class = 'Felony', id = 'P.C. 5006', months = 240, fine = 10000, color = 'red'},
--         [7] = {title = 'Threat To Life', class = 'Felony', id = 'P.C. 5007', months = 30, fine = 5000, color = 'red'},
--         [8] = {title = 'Bribery', class = 'Felony', id = 'P.C. 5008', months = 15, fine = 4000, color = 'red'},
--         [9] = {title = 'Corruption', class = 'Felony', id = 'P.C. 5009', months = 120, fine = 50000, color = 'red'},
--         [10] = {title = 'Embezzlement', class = 'Felony', id = 'P.C. 5010', months = 90, fine = 6000, color = 'red'},
--         [11] = {title = 'Extortion', class = 'Felony', id = 'P.C. 5011', months = 150, fine = 10000, color = 'v'},
--         [12] = {title = 'Fraud', class = 'Felony', id = 'P.C. 5012', months = 60, fine = 10000, color = 'red'},
--         [13] = {title = 'Money Laundering', class = 'Felony', id = 'P.C. 5013', months = 30, fine = 5000, color = 'red'},
--         [14] = {title = 'Racketeering / RICO', class = 'Felony', id = 'P.C. 5014', months = 99999999999, fine = 30000, color = 'red'},
--         [15] = {title = 'Attempted Murder of a LEO', class = 'Felony', id = 'P.C. 5015', months = 125, fine = 17500, color = 'red'},
--     },
--     [4] = {
--         [1] = {title = 'Animal Cruelty', class = 'Misdemeanor', id = 'P.C. 6001', months = 15, fine = 3000, color = 'green'},
--         [2] = {title = 'Battery', class = 'Misdemeanor', id = 'P.C. 6002', months = 15, fine = 3000, color = 'green'},
--         [3] = {title = 'Breach of the Peace', class = 'Misdemeanor', id = 'P.C. 6003', months = 10, fine = 2000, color = 'green'},
--         [4] = {title = 'Break and Entering', class = 'Misdemeanor', id = 'P.C. 6004', months = 20, fine = 2500, color = 'green'},
--         [5] = {title = 'Criminal Damage', class = 'Misdemeanor', id = 'P.C. 6005', months = 20, fine = 2500, color = 'green'},
--         [6] = {title = 'Disobeying a Lawful Order', class = 'Misdemeanor', id = 'P.C. 6006', months = 30, fine = 5000, color = 'green'},
--         [7] = {title = 'Failure to Identify', class = 'Misdemeanor', id = 'P.C. 6007', months = 0, fine = 1000, color = 'green'},
--         [8] = {title = 'False Report', class = 'Misdemeanor', id = 'P.C. 6008', months = 0, fine = 5000, color = 'green'},
--         [9] = {title = 'Harassment', class = 'Misdemeanor', id = 'P.C. 6009', months = 30, fine = 2000, color = 'green'},
--         [10] = {title = 'Illegal Gambling', class = 'Misdemeanor', id = 'P.C. 6010', months = 60, fine = 10000, color = 'green'},
--         [11] = {title = 'Indecent Exposure', class = 'Misdemeanor', id = 'P.C. 6011', months = 15, fine = 1500, color = 'green'},
--         [12] = {title = 'Jaywalking', class = 'Misdemeanor', id = 'P.C. 6012', months = 0, fine = 250, color = 'green'},
--         [13] = {title = 'Open Carry Violation', class = 'Misdemeanor', id = 'P.C. 6013', months = 30, fine = 500, color = 'green'},
--         [14] = {title = 'Poaching', class = 'Misdemeanor', id = 'P.C. 6014', months = 15, fine = 1000, color = 'green'},
--         [15] = {title = 'Possession Of Class 1 Drug (Personal Use)', class = 'Misdemeanor', id = 'P.C. 6015', months = 0, fine = 1000, color = 'green'},
--         [16] = {title = 'Possession Of Class 1 Drug With Intent To Supply', class = 'Misdemeanor', id = 'P.C. 6016', months = 30, fine = 2500, color = 'green'},
--         [17] = {title = 'Prostitution', class = 'Misdemeanor', id = 'P.C. 6017', months = 30, fine = 5000, color = 'green'},
--         [18] = {title = 'Public Intoxication', class = 'Misdemeanor', id = 'P.C. 6018', months = 15, fine = 750, color = 'green'},
--         [19] = {title = 'Public Urination', class = 'Misdemeanor', id = 'P.C. 6019', months = 15, fine = 750, color = 'green'},
--         [20] = {title = 'Resisting Arrest', class = 'Misdemeanor', id = 'P.C. 6020', months = 15, fine = 2000, color = 'green'},
--         [21] = {title = 'Stalking', class = 'Misdemeanor', id = 'P.C. 6021', months = 30, fine = 2000, color = 'green'},
--         [22] = {title = 'Theft', class = 'Misdemeanor', id = 'P.C. 6022', months = 20, fine = 3500, color = 'green'},
--         [23] = {title = 'Trespassing', class = 'Misdemeanor', id = 'P.C. 6023', months = 20, fine = 3500, color = 'green'},
--         [24] = {title = 'Unlicensed Event', class = 'Misdemeanor', id = 'P.C. 6024', months = 60, fine = 10000, color = 'green'},
--     },
--     [5] = {
--         [1] = {title = 'Careless Driving', class = 'Misdemeanor', id = 'P.C. 7001', months = 0, fine = 1000, color = 'orange'},
--         [2] = {title = 'Driving Under the Influence (DUI)', class = 'Misdemeanor', id = 'P.C. 7002', months = 30, fine = 2000, color = 'orange'},
--         [3] = {title = 'Driving without a License', class = 'Misdemeanor', id = 'P.C. 7003', months = 0, fine = 1000, color = 'orange'},
--         [4] = {title = 'Taking Without Owners Consent', class = 'Misdemeanor', id = 'P.C. 7004', months = 15, fine = 1000, color = 'orange'},
--         [5] = {title = 'Driving Non-Street Legal Vehicle', class = 'Misdemeanor', id = 'P.C. 7005', months = 0, fine = 300, color = 'orange'},
--         [6] = {title = 'Excessive Vehicle Noise', class = 'Misdemeanor', id = 'P.C. 7006', months = 0, fine = 100, color = 'orange'},
--         [7] = {title = 'Failure to Maintain a Lane', class = 'Misdemeanor', id = 'P.C. 7007', months = 0, fine = 150, color = 'orange'},
--         [8] = {title = 'Failure to Stop', class = 'Misdemeanor', id = 'P.C. 7008', months = 0, fine = 200, color = 'orange'},
--         [9] = {title = 'Failure to Yield to an Emergency Vehicle', class = 'Misdemeanor', id = 'P.C. 7009', months = 0, fine = 320, color = 'orange'},
--         [10] = {title = 'Illegal Lighting Equipment', class = 'Misdemeanor', id = 'P.C. 7010', months = 0, fine = 300, color = 'orange'},
--         [11] = {title = 'Illegal Parking', class = 'Misdemeanor', id = 'P.C. 7011', months = 0, fine = 150, color = 'orange'},
--         [12] = {title = 'Illegal U-turn', class = 'Misdemeanor', id = 'P.C. 7012', months = 0, fine = 400, color = 'orange'},
--         [13] = {title = 'Obstructing Traffic', class = 'Misdemeanor', id = 'P.C. 7013', months = 0, fine = 400, color = 'orange'},
--         [14] = {title = 'Operation of an Unroadworthy Vehicle', class = 'Misdemeanor', id = 'P.C. 7014', months = 0, fine = 400, color = 'orange'},
--         [15] = {title = 'Speeding - Band 1 MPH - 10 MPH', class = 'Misdemeanor', id = 'P.C. 7015', months = 0, fine = 300, color = 'orange'},
--         [16] = {title = 'Speeding - Band 11 MPH - 25 MPH', class = 'Misdemeanor', id = 'P.C. 7016', months = 0, fine = 500, color = 'orange'},
--         [17] = {title = 'Speeding - Band 25 MPH - 40 MPH', class = 'Misdemeanor', id = 'P.C. 7017', months = 0, fine = 1000, color = 'orange'},
--         [18] = {title = 'Using Mobile Phone Whilst Driving', class = 'Misdemeanor', id = 'P.C. 7018', months = 0, fine = 200, color = 'orange'},
--     }
-- }

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Accessory to Felony', class = 'Felony', id = 'P.C. 3001', months = 30, fine = 5000, color = 'red'},
        [2] = {title = 'Aircraft Hijacking', class = 'Felony', id = 'P.C. 3002', months = 90, fine = 10000, color = 'red'},
        [3] = {title = 'Assisting An Offender', class = 'Felony', id = 'P.C. 3003', months = 15, fine = 2500, color = 'red'},
        [4] = {title = 'Breach of Airspace Regulations', class = 'Felony', id = 'P.C. 3004', months = 60, fine = 20000, color = 'red'},
        [5] = {title = 'Contempt of Court', class = 'Felony', id = 'P.C. 3005', months = 30, fine = 5000, color = 'red'},
        [6] = {title = 'Escaping Lawful Custody', class = 'Felony', id = 'P.C. 3006', months = 30, fine = 8000, color = 'red'},
        [7] = {title = 'Felony Evading Arrest', class = 'Felony', id = 'P.C. 3007', months = 15, fine = 2500, color = 'red'},
        [8] = {title = 'Human Trafficking', class = 'Felony', id = 'P.C. 3008', months = 120, fine = 8000, color = 'red'},
        [9] = {title = 'Impersonation of a Government Official', class = 'Felony', id = 'P.C. 3009', months = 60, fine = 10000, color = 'red'},
        [10] = {title = 'Jailbreak', class = 'Felony', id = 'P.C. 3010', months = 90, fine = 7500, color = 'red'},
        [11] = {title = 'Kidnapping', class = 'Felony', id = 'P.C. 3011', months = 60, fine = 4000, color = 'red'},
        [12] = {title = 'Obstruction of a Government Official', class = 'Felony', id = 'P.C. 3012', months = 20, fine = 5000, color = 'red'},
        [13] = {title = 'Obstruction of Justice', class = 'Felony', id = 'P.C. 3013', months = 20, fine = 5000, color = 'red'},
        [14] = {title = 'Perjury', class = 'Felony', id = 'P.C. 3014', months = 60, fine = 7500, color = 'red'},
        [15] = {title = 'Possession of Stolen Goods', class = 'Felony', id = 'P.C. 3015', months = 15, fine = 3000, color = 'red'},
        [16] = {title = 'Prison Break', class = 'Felony', id = 'P.C. 3016', months = 60, fine = 10000, color = 'red'},
        [17] = {title = 'Theft', class = 'Felony', id = 'P.C. 3017', months = 30, fine = 5000, color = 'red'},
        [18] = {title = 'Trespassing on Airport Property', class = 'Felony', id = 'P.C. 3018', months = 30, fine = 10000, color = 'red'},
        [19] = {title = 'Trespassing with the Intent of Theft', class = 'Felony', id = 'P.C. 3019', months = 30, fine = 5000, color = 'red'},
        [20] = {title = 'Unlawful Imprisonment', class = 'Felony', id = 'P.C. 3020', months = 30, fine = 4000, color = 'red'},
        [21] = {title = 'Witness Intimidation', class = 'Felony', id = 'P.C. 3021', months = 90, fine = 10000, color = 'red'},
        [22] = {title = 'Grand Theft Auto', class = 'Felony', id = 'P.C. 3022', months = 10, fine = 1500, color = 'red'},
        [23] = {title = 'Hit and Run', class = 'Felony', id = 'P.C. 3023', months = 60, fine = 2500, color = 'red'},
        [24] = {title = 'Reckless Driving', class = 'Felony', id = 'P.C. 3024', months = 15, fine = 2000, color = 'red'},
        [25] = {title = 'Vehicular Battery', class = 'Felony', id = 'P.C. 3025', months = 20, fine = 5000, color = 'red'},
        [26] = {title = 'Art Gallery Heist', class = 'Felony', id = 'P.C. 3026', months = 45, fine = 25000, color = 'red'},
        [27] = {title = 'Bank Robbery', class = 'Felony', id = 'P.C. 3027', months = 45, fine = 15000, color = 'red'},
        [28] = {title = 'Jewelry Heist', class = 'Felony', id = 'P.C. 3028', months = 45, fine = 7500, color = 'red'},
        [29] = {title = 'Store Robbery', class = 'Felony', id = 'P.C. 3029', months = 25, fine = 3500, color = 'red'},
        [30] = {title = 'Armed Robbery', class = 'Felony', id = 'P.C. 3030', months = 40, fine = 8000, color = 'red'},
        [31] = {title = 'Commercial break in', class = 'Felony', id = 'P.C. 3031', months = 40, fine = 8000, color = 'red'},
        [32] = {title = 'Yacht Heist', class = 'Felony', id = 'P.C. 3032', months = 45, fine = 25000, color = 'red'},
    },
    [2] = {
        [1] = {title = 'Class 1 Drug Trafficking', class = 'Felony', id = 'P.C. 4001', months = 15, fine = 2500, color = 'red'},
        [2] = {title = 'Class 2 Drug Trafficking', class = 'Felony', id = 'P.C. 4002', months = 20, fine = 5000, color = 'red'},
        [3] = {title = 'Class 3 Drug Trafficking', class = 'Felony', id = 'P.C. 4003', months = 30, fine = 10000, color = 'red'},
        [4] = {title = 'Drug Manufacture & Supply', class = 'Felony', id = 'P.C. 4004', months = 60, fine = 10000, color = 'red'},
        [5] = {title = 'Industrial Scale Drug Manufacture & Supply', class = 'Felony', id = 'P.C. 4005', months = 180, fine = 50000, color = 'red'},
        [6] = {title = 'Possession Of Class 2 Drug', class = 'Felony', id = 'P.C. 4006', months = 0, fine = 2000, color = 'red'},
        [7] = {title = 'Possession Of Class 2 Drug With Intent To Supply', class = 'Felony', id = 'P.C. 4007', months = 15, fine = 3500, color = 'red'},
        [8] = {title = 'Possession of Class 3 drug', class = 'Felony', id = 'P.C. 4008', months = 10, fine = 5000, color = 'red'},
        [9] = {title = 'Possession of Class 3 Drug With Intent To Supply', class = 'Felony', id = 'P.C. 4009', months = 25, fine = 6000, color = 'red'},
        [10] = {title = 'Brandishing a Weapon', class = 'Felony', id = 'P.C. 4010', months = 15, fine = 2000, color = 'red'},
        [11] = {title = 'Illegal Weapons Crafting', class = 'Felony', id = 'P.C. 4011', months = 120, fine = 20000, color = 'red'},
        [12] = {title = 'Illegal Weapons Trafficking', class = 'Felony', id = 'P.C. 4012', months = 240, fine = 50000, color = 'red'},
        [13] = {title = 'Industrial scale Illegal Weapons Crafting', class = 'Felony', id = 'P.C. 4013', months = 360, fine = 100000, color = 'red'},
        [14] = {title = 'Possession of a Firearm Without a License', class = 'Felony', id = 'P.C. 4014', months = 10, fine = 3000, color = 'red'},
        [15] = {title = 'Possession of an Illegal Firearm Class 1', class = 'Felony', id = 'P.C. 4015', months = 20, fine = 5000, color = 'red'},
        [16] = {title = 'Possession of an Illegal Firearm Class 2', class = 'Felony', id = 'P.C. 4016', months = 35, fine = 7000, color = 'red'},
        [17] = {title = 'Possession of an Illegal Firearm Class 3', class = 'Felony', id = 'P.C. 4017', months = 60, fine = 12500, color = 'red'},
        [18] = {title = 'Possession of Explosives', class = 'Felony', id = 'P.C. 4018', months = 20, fine = 5000, color = 'red'},
        [19] = {title = 'Unlawful Discharge of a Firearm', class = 'Felony', id = 'P.C. 4019', months = 15, fine = 5000, color = 'red'},
    },
    [3] = {
        [1] = {title = 'Assault', class = 'Felony', id = 'P.C. 5001', months = 15, fine = 2000, color = 'red'},
        [2] = {title = 'Assault with a Deadly Weapon', class = 'Felony', id = 'P.C. 5002', months = 30, fine = 5000, color = 'red'},
        [3] = {title = 'Attempted Murder', class = 'Felony', id = 'P.C. 5003', months = 45, fine = 7500, color = 'red'},
        [4] = {title = 'Manslaughter', class = 'Felony', id = 'P.C. 5004', months = 25, fine = 5000, color = 'red'},
        [5] = {title = 'Murder', class = 'Felony', id = 'P.C. 5005', months = 999999999, fine = 20000, color = 'red'},
        [6] = {title = 'Terroristic Threat', class = 'Felony', id = 'P.C. 5006', months = 240, fine = 10000, color = 'red'},
        [7] = {title = 'Threat To Life', class = 'Felony', id = 'P.C. 5007', months = 30, fine = 5000, color = 'red'},
        [8] = {title = 'Bribery', class = 'Felony', id = 'P.C. 5008', months = 15, fine = 4000, color = 'red'},
        [9] = {title = 'Corruption', class = 'Felony', id = 'P.C. 5009', months = 120, fine = 50000, color = 'red'},
        [10] = {title = 'Embezzlement', class = 'Felony', id = 'P.C. 5010', months = 90, fine = 6000, color = 'red'},
        [11] = {title = 'Extortion', class = 'Felony', id = 'P.C. 5011', months = 150, fine = 10000, color = 'v'},
        [12] = {title = 'Fraud', class = 'Felony', id = 'P.C. 5012', months = 60, fine = 10000, color = 'red'},
        [13] = {title = 'Money Laundering', class = 'Felony', id = 'P.C. 5013', months = 30, fine = 5000, color = 'red'},
        [14] = {title = 'Racketeering / RICO', class = 'Felony', id = 'P.C. 5014', months = 99999999999, fine = 30000, color = 'red'},
        [15] = {title = 'Attempted Murder of an Government Official', class = 'Felony', id = 'P.C. 5015', months = 125, fine = 17500, color = 'red'},
    },
    [4] = {
        [1] = {title = 'Animal Cruelty', class = 'Misdemeanor', id = 'P.C. 6001', months = 15, fine = 3000, color = 'green'},
        [2] = {title = 'Battery', class = 'Misdemeanor', id = 'P.C. 6002', months = 15, fine = 3000, color = 'green'},
        [3] = {title = 'Breach of the Peace', class = 'Misdemeanor', id = 'P.C. 6003', months = 10, fine = 2000, color = 'green'},
        [4] = {title = 'Break and Entering', class = 'Misdemeanor', id = 'P.C. 6004', months = 20, fine = 2500, color = 'green'},
        [5] = {title = 'Criminal Damage', class = 'Misdemeanor', id = 'P.C. 6005', months = 20, fine = 2500, color = 'green'},
        [6] = {title = 'Disobeying a Lawful Order', class = 'Misdemeanor', id = 'P.C. 6006', months = 30, fine = 5000, color = 'green'},
        [7] = {title = 'Failure to Identify', class = 'Misdemeanor', id = 'P.C. 6007', months = 0, fine = 1000, color = 'green'},
        [8] = {title = 'False Report', class = 'Misdemeanor', id = 'P.C. 6008', months = 0, fine = 5000, color = 'green'},
        [9] = {title = 'Harassment', class = 'Misdemeanor', id = 'P.C. 6009', months = 30, fine = 2000, color = 'green'},
        [10] = {title = 'Illegal Gambling', class = 'Misdemeanor', id = 'P.C. 6010', months = 60, fine = 10000, color = 'green'},
        [11] = {title = 'Indecent Exposure', class = 'Misdemeanor', id = 'P.C. 6011', months = 15, fine = 1500, color = 'green'},
        [12] = {title = 'Jaywalking', class = 'Misdemeanor', id = 'P.C. 6012', months = 0, fine = 250, color = 'green'},
        [13] = {title = 'Open Carry Violation', class = 'Misdemeanor', id = 'P.C. 6013', months = 30, fine = 500, color = 'green'},
        [14] = {title = 'Poaching', class = 'Misdemeanor', id = 'P.C. 6014', months = 15, fine = 1000, color = 'green'},
        [15] = {title = 'Possession Of Class 1 Drug (Personal Use)', class = 'Misdemeanor', id = 'P.C. 6015', months = 0, fine = 1000, color = 'green'},
        [16] = {title = 'Possession Of Class 1 Drug With Intent To Supply', class = 'Misdemeanor', id = 'P.C. 6016', months = 30, fine = 2500, color = 'green'},
        [17] = {title = 'Prostitution', class = 'Misdemeanor', id = 'P.C. 6017', months = 30, fine = 5000, color = 'green'},
        [18] = {title = 'Public Intoxication', class = 'Misdemeanor', id = 'P.C. 6018', months = 15, fine = 750, color = 'green'},
        [19] = {title = 'Public Urination', class = 'Misdemeanor', id = 'P.C. 6019', months = 15, fine = 750, color = 'green'},
        [20] = {title = 'Resisting Arrest', class = 'Misdemeanor', id = 'P.C. 6020', months = 15, fine = 2000, color = 'green'},
        [21] = {title = 'Stalking', class = 'Misdemeanor', id = 'P.C. 6021', months = 30, fine = 2000, color = 'green'},
        [22] = {title = 'Theft', class = 'Misdemeanor', id = 'P.C. 6022', months = 20, fine = 3500, color = 'green'},
        [23] = {title = 'Trespassing', class = 'Misdemeanor', id = 'P.C. 6023', months = 20, fine = 3500, color = 'green'},
        [24] = {title = 'Unlicensed Event', class = 'Misdemeanor', id = 'P.C. 6024', months = 60, fine = 10000, color = 'green'},
    },
    [5] = {
        [1] = {title = 'Careless Driving', class = 'Misdemeanor', id = 'P.C. 7001', months = 0, fine = 1000, color = 'orange'},
        [2] = {title = 'Driving Under the Influence (DUI)', class = 'Misdemeanor', id = 'P.C. 7002', months = 30, fine = 2000, color = 'orange'},
        [3] = {title = 'Driving without a License', class = 'Misdemeanor', id = 'P.C. 7003', months = 0, fine = 1000, color = 'orange'},
        [4] = {title = 'Taking Without Owners Consent', class = 'Misdemeanor', id = 'P.C. 7004', months = 15, fine = 1000, color = 'orange'},
        [5] = {title = 'Driving Non-Street Legal Vehicle', class = 'Misdemeanor', id = 'P.C. 7005', months = 0, fine = 300, color = 'orange'},
        [6] = {title = 'Excessive Vehicle Noise', class = 'Misdemeanor', id = 'P.C. 7006', months = 0, fine = 100, color = 'orange'},
        [7] = {title = 'Failure to Maintain a Lane', class = 'Misdemeanor', id = 'P.C. 7007', months = 0, fine = 150, color = 'orange'},
        [8] = {title = 'Failure to Stop', class = 'Misdemeanor', id = 'P.C. 7008', months = 0, fine = 200, color = 'orange'},
        [9] = {title = 'Failure to Yield to an Emergency Vehicle', class = 'Misdemeanor', id = 'P.C. 7009', months = 0, fine = 320, color = 'orange'},
        [10] = {title = 'Illegal Lighting Equipment', class = 'Misdemeanor', id = 'P.C. 7010', months = 0, fine = 300, color = 'orange'},
        [11] = {title = 'Illegal Parking', class = 'Misdemeanor', id = 'P.C. 7011', months = 0, fine = 150, color = 'orange'},
        [12] = {title = 'Illegal U-turn', class = 'Misdemeanor', id = 'P.C. 7012', months = 0, fine = 400, color = 'orange'},
        [13] = {title = 'Obstructing Traffic', class = 'Misdemeanor', id = 'P.C. 7013', months = 0, fine = 400, color = 'orange'},
        [14] = {title = 'Operation of an Unroadworthy Vehicle', class = 'Misdemeanor', id = 'P.C. 7014', months = 0, fine = 400, color = 'orange'},
        [15] = {title = 'Speeding - Band 1 MPH - 10 MPH', class = 'Misdemeanor', id = 'P.C. 7015', months = 0, fine = 300, color = 'orange'},
        [16] = {title = 'Speeding - Band 11 MPH - 25 MPH', class = 'Misdemeanor', id = 'P.C. 7016', months = 0, fine = 500, color = 'orange'},
        [17] = {title = 'Speeding - Band 25 MPH - 40 MPH', class = 'Misdemeanor', id = 'P.C. 7017', months = 0, fine = 1000, color = 'orange'},
        [18] = {title = 'Using Mobile Phone Whilst Driving', class = 'Misdemeanor', id = 'P.C. 7018', months = 0, fine = 200, color = 'orange'},
    }
}


Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = true,
    ['bcso'] = true,
    ['sast'] = true,
    ['sasp'] = true,
    ['doc'] = true,
    ['sapr'] = true,
    ['pa'] = true -- yucky
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
}

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = true,
	},
    ['sasp'] = {
		[4] = true,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = { 
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}
